### ISSUE TITLE
How to get the latent representatio for each user?

### ISSUE THREAD

**Issue by gilcanetasdias** [mkfilipiuk/VAE-CF#1]
Hi there, 
What is the best way to get the latent representation (embeddings) for each user?
thanks in advance

**Comment by mkfilipiuk** [comment]
Hi @gilcanetasdias,
there is no dedicated way to get only the latent representation of users. However it's python, so you can play with objects however you like.
When you have a trained [VAE](https://github.com/mkfilipiuk/VAE-CF/blob/master/vae/models/Mult_VAE_training.py#L21) model, just get a `_VAE` attribute (https://github.com/mkfilipiuk/VAE-CF/blob/master/vae/models/Mult_VAE_model.py#L45) and then select [the encoder](https://github.com/mkfilipiuk/VAE-CF/blob/master/vae/models/Mult_VAE_model.py#L16) from it.   
Now just run session on it and you'll get the embeddings of data that you pass there :)

**Comment by gilcanetasdias** [comment]
Thank you very much for the answer!
So it should be something like this?
`vae.vae.encoder(test_data_input, training=False)`
`embeddings = vae.session.run()`

To transform the data is better to use the batch_iterator_val right?
I am more used to work with pytorch 😅! 
Thank you for the help one more time!

**Comment by mkfilipiuk** [comment]
this encoder you have to pass to session run, so sth more like:
```
embeddings = session.run(vae.vae.encoder(test_data_input, training=False))
```
but you were close 🙂

**Comment by gilcanetasdias** [comment]
Almost there 😅! 
I wrote this inside  the vae.test() to use the batch_iterator_val to transform my data.
`with tf.Session() as sess:`
                   ` embeddings = sess.run(self.vae.encoder({self.inputs_validation: (idxs, vals)}), training=False)`

But when I run I have the following error:
`raise RuntimeError("Graph is finalized and cannot be modified.")`
